// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfyFhg140qLDngdhivy2lAXo5r9QvpPw8',
    appId: '1:311993576664:web:a9ffc2282a47fae9b4fbad',
    messagingSenderId: '311993576664',
    projectId: 'nossas-contas-app-c432d',
    authDomain: 'nossas-contas-app-c432d.firebaseapp.com',
    storageBucket: 'nossas-contas-app-c432d.firebasestorage.app',
    measurementId: 'G-ZT6SHTFM9F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrMCuJBKrojKrcc-Ml3bprEQ6MdiUxxEE',
    appId: '1:311993576664:android:ec0b946a839133f6b4fbad',
    messagingSenderId: '311993576664',
    projectId: 'nossas-contas-app-c432d',
    storageBucket: 'nossas-contas-app-c432d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtPAcBNythNRxZXTaISnpSST9O3RbTCwc',
    appId: '1:311993576664:ios:b706b40db568a071b4fbad',
    messagingSenderId: '311993576664',
    projectId: 'nossas-contas-app-c432d',
    storageBucket: 'nossas-contas-app-c432d.firebasestorage.app',
    iosBundleId: 'com.example.nossasContas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtPAcBNythNRxZXTaISnpSST9O3RbTCwc',
    appId: '1:311993576664:ios:b706b40db568a071b4fbad',
    messagingSenderId: '311993576664',
    projectId: 'nossas-contas-app-c432d',
    storageBucket: 'nossas-contas-app-c432d.firebasestorage.app',
    iosBundleId: 'com.example.nossasContas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfyFhg140qLDngdhivy2lAXo5r9QvpPw8',
    appId: '1:311993576664:web:7dc93c779f7f3e5ab4fbad',
    messagingSenderId: '311993576664',
    projectId: 'nossas-contas-app-c432d',
    authDomain: 'nossas-contas-app-c432d.firebaseapp.com',
    storageBucket: 'nossas-contas-app-c432d.firebasestorage.app',
    measurementId: 'G-CV6NZM6392',
  );
}
